# Global options
baseurl = "https://causalinfo.github.io/"
canonifyurls = true
languagecode = "en"
theme = "crl-uai-2022-theme"
disableKinds = ["taxonomyTerm"]

# Params that are used in <head>
[params]
  supertitle = "Learning From Data With Information Theory and Causal Inference"
  title = "A minisymposium @ the 2024 SIAM Annual Meeting"
  subtitle = "July 9th & 12th 2024"
  author = "Joseph Janssen, Vincent Guan, Elina Robeva"
  description = "2024 SIAM Annual Meeting minisymposium on 'Learning From Data With Information Theory and Causal Inference' "
  keywords = ["minisymposium", "causal inference", "information theory"]

# Options for Markdown renderer
[markup.goldmark.renderer]
  unsafe = true
  xHTML = true

# Main menu
[[menu.main]]
    name = "Call for Papers"
    url  = "/call-for-papers"
    weight = 1
[[menu.main]]
    name = "About"
    url  = "/about"
    weight = 2
[[menu.main]]
    name = "Dates"
    url  = "/dates"
    weight = 3
[[menu.main]]
    name = "Formatting Instructions"
    url  = "/formatting-instructions"
    weight = 4
[[menu.main]]
    name = "Organisers and Reviewers"
    url  = "/organisers-reviewers"
    weight = 5
[[menu.main]]
    name = "Accepted Papers"
    url  = "/accepted-papers"
    weight = 6
[[menu.main]]
    name = "Past Workshops"
    url  = "/past-workshops"
    weight = 7
[[menu.main]]
    name = "Schedule and Format"
    url  = "/schedule-format"
    weight = 8
[[menu.main]]
    name = "Invited Speakers and Panelists"
    url  = "/invited-speakers"
    weight = 9
# [[menu.main]]
#     name = "Slides and Recording"
#     url  = "/slides-recording"
#     weight = 10
